# Generated by Django 2.1.7 on 2019-03-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insider', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('owner_type', models.CharField(max_length=100)),
                ('shares_traded', models.BigIntegerField()),
                ('last_price', models.FloatField()),
                ('shares_held', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_and_trades.Ticker')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_and_trades.Ticker'),
        ),
    ]
