# Generated by Django 2.1.7 on 2019-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_trades', '0002_auto_20190317_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
