# Generated by Django 2.1.7 on 2019-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_trades', '0004_auto_20190317_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(),
        ),
    ]
