# Generated by Django 2.1.7 on 2019-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_trades', '0005_auto_20190317_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='last_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
